apiVersion: network.openshift.io/v1
kind: EgressNetworkPolicy
metadata:
  name: default-rules
spec:
  egress: # A collection of egress firewall policy rule objects.
  - type: Allow
    to:
      dnsName: docs.openshift.com
  - type: Deny
    to:
      cidrSelector: 0.0.0.0/0
